                                        Artificial Neural Networks

In [1]:
# @author: piyush taneja
#Installing Theano
#Pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

#Installing Tensorflow
#Install Tensorflow from the website: https://www.tensorflow.org/versions/rO.11/get_started

#Installing Keras
#Pip install --upgrade keras

In [2]:
# Part-1 Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [24]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,26,15738191,Maclean,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,28,15700772,Nebechi,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,15587133,Thompson,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,9972,15721377,Chou,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,9973,15747927,Ch'in,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,9975,15695474,Barker,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,9977,15656062,Azikiwe,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,9978,15579969,Mancini,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,9979,15703563,P'eng,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X=X[: ,1:]

In [10]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split  # we replaced cross_validation by model_selection due to spyder updation which has model_selection as value 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [8]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [11]:
# Part 2 - Now let's make the ANN!

#Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [12]:
# Inintialising the ANN
classifier = Sequential()

In [13]:
#Adding the input layer and first hidden layer
classifier.add(Dense(output_dim=6 , init='uniform' , activation='relu' , input_dim=11))
#output_dim is used to tell no. of hidden cells in first layer i.e is calculated by taking average of (no. of input layer + no. of output layer)/2
# We need to use input_dim only for the first hidden layer after that all the others hidden layers will automatically understand about it. It tells about no. of input variables in hidden layer
# init='uniform' is used to initialize the weights uniformly.
# Here we use activation function whose value is 'relu' i.e rectifier activation function.

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`

In [14]:
# Adding second Hidden layer
classifier.add(Dense(output_dim=6 , init='uniform' , activation='relu')) # Not required to write input_dim as written already for first layer.

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`

In [15]:
classifier

In [16]:
# Adding the output layers
classifier.add(Dense(output_dim=1 , init='uniform' , activation='sigmoid' )) # Here since we are finding the o/p layer so value of activation is 'sigmoid' as sigmoid func is used at output side.

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`

In [18]:
#Compiling the ANN
classifier.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

In [19]:
#Fitting the ANN to the Training set
classifier.fit(X_train , y_train , batch_size=10 , nb_epoch=100)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.

Epoch 1/100
8000/8000 [==============================] - 4s 463us/step - loss: 0.6118 - acc: 0.7979
Epoch 2/100
8000/8000 [==============================] - 3s 352us/step - loss: 0.4895 - acc: 0.8329
Epoch 3/100
8000/8000 [==============================] - 3s 314us/step - loss: 0.4228 - acc: 0.8461
Epoch 4/100
8000/8000 [==============================] - 2s 294us/step - loss: 0.3922 - acc: 0.8544
Epoch 5/100
8000/8000 [==============================] - 3s 420us/step - loss: 0.3758 - acc: 0.8532
Epoch 6/100
8000/8000 [==============================] - 3s 374us/step - loss: 0.3666 - acc: 0.8561
Epoch 7/100
8000/8000 [==============================] - 3s 335us/step - loss: 0.3613 - acc: 0.8536
Epoch 8/100
8000/8000 [==============================] - 3s 323us/step - loss: 0.3573 - acc: 0.8555
Epoch 9/100
8000/8000 [==============================] - 2s 283us/step - loss: 0.3554 - acc: 0.8564
Epoch 10/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.3527 - acc: 0.8582
Epoch 11/100
8000/8000 [==============================] - 2s 235us/step - loss: 0.3515 - acc: 0.8597
Epoch 12/100
8000/8000 [==============================] - 2s 290us/step - loss: 0.3501 - acc: 0.8587
Epoch 13/100
8000/8000 [==============================] - 2s 249us/step - loss: 0.3491 - acc: 0.8599
Epoch 14/100
8000/8000 [==============================] - 3s 398us/step - loss: 0.3485 - acc: 0.8605 0s - loss: 0.3509 - acc: 0.8 - ETA: 0s - loss: 0.3495 - ac
Epoch 15/100
8000/8000 [==============================] - 3s 434us/step - loss: 0.3475 - acc: 0.8592
Epoch 16/100
8000/8000 [==============================] - 3s 402us/step - loss: 0.3466 - acc: 0.8601
Epoch 17/100
8000/8000 [==============================] - 4s 460us/step - loss: 0.3459 - acc: 0.8609
Epoch 18/100
8000/8000 [==============================] - ETA: 0s - loss: 0.3447 - acc: 0.861 - 3s 324us/step - loss: 0.3453 - acc: 0.8609
Epoch 19/100
8000/8000 [==============================] - 3s 326us/step - loss: 0.3449 - acc: 0.8622
Epoch 20/100
8000/8000 [==============================] - 4s 454us/step - loss: 0.3440 - acc: 0.8606
Epoch 21/100
8000/8000 [==============================] - 3s 313us/step - loss: 0.3433 - acc: 0.8615 0s - loss: 0.3432 - acc: 0.8
Epoch 22/100
8000/8000 [==============================] - 2s 306us/step - loss: 0.3430 - acc: 0.8610
Epoch 23/100
8000/8000 [==============================] - 2s 262us/step - loss: 0.3420 - acc: 0.8624
Epoch 24/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3425 - acc: 0.8590
Epoch 25/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.3424 - acc: 0.8594
Epoch 26/100
8000/8000 [==============================] - 2s 259us/step - loss: 0.3416 - acc: 0.8615
Epoch 27/100
8000/8000 [==============================] - 3s 376us/step - loss: 0.3406 - acc: 0.8621 0s - loss: 0.3394
Epoch 28/100
8000/8000 [==============================] - 6s 704us/step - loss: 0.3406 - acc: 0.8601
Epoch 29/100
8000/8000 [==============================] - 4s 551us/step - loss: 0.3404 - acc: 0.8626
Epoch 30/100
8000/8000 [==============================] - 3s 408us/step - loss: 0.3403 - acc: 0.8615 1s - loss:
Epoch 31/100
8000/8000 [==============================] - 3s 335us/step - loss: 0.3397 - acc: 0.8611
Epoch 32/100
8000/8000 [==============================] - 4s 508us/step - loss: 0.3397 - acc: 0.8599 0s - loss: 0.
Epoch 33/100
8000/8000 [==============================] - 2s 306us/step - loss: 0.3396 - acc: 0.8616
Epoch 34/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.3392 - acc: 0.8622
Epoch 35/100
8000/8000 [==============================] - 2s 241us/step - loss: 0.3391 - acc: 0.8626
Epoch 36/100
8000/8000 [==============================] - 2s 266us/step - loss: 0.3386 - acc: 0.8622
Epoch 37/100
8000/8000 [==============================] - 3s 356us/step - loss: 0.3387 - acc: 0.8620 1s - loss: 0.3449 - acc:  - ETA: 0s - loss: 0.3416 -
Epoch 38/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.3384 - acc: 0.8641 1s - loss: 0
Epoch 39/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3382 - acc: 0.8615
Epoch 40/100
8000/8000 [==============================] - 2s 233us/step - loss: 0.3380 - acc: 0.8634
Epoch 41/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.3382 - acc: 0.8614
Epoch 42/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.3376 - acc: 0.8624
Epoch 43/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3376 - acc: 0.8595
Epoch 44/100
8000/8000 [==============================] - 2s 235us/step - loss: 0.3376 - acc: 0.8630
Epoch 45/100
8000/8000 [==============================] - 3s 321us/step - loss: 0.3377 - acc: 0.8622 0s - loss: 0.3364 - acc
Epoch 46/100
8000/8000 [==============================] - 2s 303us/step - loss: 0.3374 - acc: 0.8624
Epoch 47/100
8000/8000 [==============================] - 2s 229us/step - loss: 0.3371 - acc: 0.8605
Epoch 48/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.3372 - acc: 0.8615
Epoch 49/100
8000/8000 [==============================] - 2s 226us/step - loss: 0.3367 - acc: 0.8609
Epoch 50/100
8000/8000 [==============================] - 2s 251us/step - loss: 0.3367 - acc: 0.8642
Epoch 51/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.3367 - acc: 0.8591
Epoch 52/100
8000/8000 [==============================] - 3s 365us/step - loss: 0.3363 - acc: 0.8622
Epoch 53/100
8000/8000 [==============================] - 4s 442us/step - loss: 0.3362 - acc: 0.8607 2s - loss: 0.3450 - acc:  - ETA: 2s
Epoch 54/100
8000/8000 [==============================] - 3s 365us/step - loss: 0.3360 - acc: 0.8619 0s - loss: 0.3421 - acc
Epoch 55/100
8000/8000 [==============================] - 2s 260us/step - loss: 0.3362 - acc: 0.8609
Epoch 56/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3357 - acc: 0.8597
Epoch 57/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3357 - acc: 0.8634
Epoch 58/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3354 - acc: 0.8611
Epoch 59/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.3354 - acc: 0.8610
Epoch 60/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3358 - acc: 0.8625
Epoch 61/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.3349 - acc: 0.8624
Epoch 62/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3357 - acc: 0.8620
Epoch 63/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3347 - acc: 0.8630
Epoch 64/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3347 - acc: 0.8606
Epoch 65/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3346 - acc: 0.8606
Epoch 66/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3348 - acc: 0.8632
Epoch 67/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3350 - acc: 0.8611
Epoch 68/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3348 - acc: 0.8635
Epoch 69/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3346 - acc: 0.8619
Epoch 70/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3341 - acc: 0.8624
Epoch 71/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3353 - acc: 0.8619
Epoch 72/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.3342 - acc: 0.8624
Epoch 73/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3345 - acc: 0.8620
Epoch 74/100
8000/8000 [==============================] - ETA: 0s - loss: 0.3353 - acc: 0.862 - 2s 190us/step - loss: 0.3342 - acc: 0.8624
Epoch 75/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.3341 - acc: 0.8615
Epoch 76/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3341 - acc: 0.8634
Epoch 77/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3338 - acc: 0.8629
Epoch 78/100

8000/8000 [==============================] - 1s 175us/step - loss: 0.3338 - acc: 0.8631
Epoch 79/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3338 - acc: 0.8645
Epoch 80/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3338 - acc: 0.8611
Epoch 81/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3338 - acc: 0.8641
Epoch 82/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.3340 - acc: 0.8621
Epoch 83/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.3336 - acc: 0.8629
Epoch 84/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3339 - acc: 0.8637
Epoch 85/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3342 - acc: 0.8635
Epoch 86/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3335 - acc: 0.8619
Epoch 87/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3333 - acc: 0.8644
Epoch 88/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3330 - acc: 0.8645
Epoch 89/100
8000/8000 [==============================] - 2s 231us/step - loss: 0.3335 - acc: 0.8635
Epoch 90/100
8000/8000 [==============================] - 3s 313us/step - loss: 0.3340 - acc: 0.8609
Epoch 91/100
8000/8000 [==============================] - 3s 322us/step - loss: 0.3337 - acc: 0.8627
Epoch 92/100
8000/8000 [==============================] - 3s 331us/step - loss: 0.3331 - acc: 0.8636
Epoch 93/100
8000/8000 [==============================] - 2s 241us/step - loss: 0.3336 - acc: 0.8622
Epoch 94/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3333 - acc: 0.8626
Epoch 95/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3330 - acc: 0.8617
Epoch 96/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3324 - acc: 0.8624
Epoch 97/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.3335 - acc: 0.8627
Epoch 98/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3332 - acc: 0.8615
Epoch 99/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3329 - acc: 0.8640
Epoch 100/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.3329 - acc: 0.8617

In [20]:
# Part 3 - Making the predictions and Evaluating the model
 
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) # Here this is done to convert probability into true or false i.e whether proba. of customer leaving bank is>0.5 then true else false
# Making the confusion Matrix
from sklearn.metrics import confusion_matrix  #Here confusion_matrix is a function and not a class as class has capitalletters at the beginning.
cm = confusion_matrix(y_test , y_pred)

In [21]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [22]:
cm

array([[1528,   67],
       [ 200,  205]], dtype=int64)

In [23]:
# Accuracy
(1534+151)/2000

0.8425